### ISSUE TITLE
unhandled exception script

### ISSUE THREAD

**Issue by caobidawang** [Kinuseka/DBD-Region-Changer#2]
![DBDRegion_pxVJm8SCut](https://github.com/Kinuseka/DBD-Region-Changer/assets/14091012/1e7ad07b-c4f4-45ca-b0d4-f602c7142fef)

**Comment by Kinuseka** [comment]
Seems to be a problem with how the binary is compiled. Will be fixed soon

**Comment by Kinuseka** [comment]
Recompiled and reuploaded binary on https://github.com/Kinuseka/DBD-Region-Changer/releases/latest

Do redownload and try again.
