### ISSUE TITLE
Lack of Hong Kong servers

### ISSUE THREAD

**Issue by caobidawang** [Kinuseka/DBD-Region-Changer#3]
Asia servers lack Hong Kong

**Comment by Kinuseka** [comment]
The servers available are provided by [AWS gamelift](https://docs.aws.amazon.com/general/latest/gr/gamelift.html) which is something out of my control. 

If you have a suggestion regarding the lack of servers in that particular region please contact the relating department for [AWS gamelift](https://aws.amazon.com/gamelift/)

**Comment by caobidawang** [comment]
ec2.ap-east-1.amazonaws.com
This is the address of the Hong Kong server

**Comment by Kinuseka** [comment]
DBD uses gamelift servers as shown here: https://docs.aws.amazon.com/general/latest/gr/gamelift.html
```
US East (N. Virginia) | us-east-1 | gamelift.us-east-1.amazonaws.com | HTTPS
US West (N. California) | us-west-1 | gamelift.us-west-1.amazonaws.com | HTTPS
US West (Oregon) | us-west-2 | gamelift.us-west-2.amazonaws.com | HTTPS
Asia Pacific (Mumbai) | ap-south-1 | gamelift.ap-south-1.amazonaws.com | HTTPS
Asia Pacific (Seoul) | ap-northeast-2 | gamelift.ap-northeast-2.amazonaws.com | HTTPS
Asia Pacific (Singapore) | ap-southeast-1 | gamelift.ap-southeast-1.amazonaws.com | HTTPS
Asia Pacific (Sydney) | ap-southeast-2 | gamelift.ap-southeast-2.amazonaws.com | HTTPS
Asia Pacific (Tokyo) | ap-northeast-1 | gamelift.ap-northeast-1.amazonaws.com | HTTPS
Canada (Central) | ca-central-1 | gamelift.ca-central-1.amazonaws.com | HTTPS
Europe (Frankfurt) | eu-central-1 | gamelift.eu-central-1.amazonaws.com | HTTPS
Europe (Ireland) | eu-west-1 | gamelift.eu-west-1.amazonaws.com | HTTPS
Europe (London) | eu-west-2 | gamelift.eu-west-2.amazonaws.com | HTTPS
South America (São Paulo) | sa-east-1 | gamelift.sa-east-1.amazonaws.com | HTTPS
```

Gamelift does not have a hongkong server

**Comment by joshuawalker** [comment]
@Kinuseka Hong Kong does have a GameLift service (since 2021) but it is not enabled by default: https://docs.aws.amazon.com/gamelift/latest/developerguide/setting-up-role.html

Behaviour enabled HK for DBD in version 8.0.0. But, due to how GameLift seems to work in these opt-in regions, I'm not sure how easy it will be add to the program.
