### ISSUE TITLE
[bug] Unicode decoding error

### ISSUE THREAD

**Issue by c0sogi** [Kinuseka/DBD-Region-Changer#5]
![화면 캡처 2024-08-31 204803](https://github.com/user-attachments/assets/3a56ccca-511a-43ca-9125-38d004b9283f)

It raises `cp949 decoding error` on startup.
I think the text io operation should be done with `encoding='utf-8'` explictly.

**Comment by Kinuseka** [comment]
should be fixed on commit [5c2c04f](https://github.com/Kinuseka/DBD-Region-Changer/commit/5c2c04f0cf7bb23404908f9ac9e25eeef37f62a3)
