### ISSUE TITLE
Hostnames have changed

### ISSUE THREAD

**Issue by htmldoug** [Kinuseka/DBD-Region-Changer#6]
As of Dead by Daylight 8.4.0, the relevant hostnames have changed. The ones set by tool (as of release 1.1.4) no longer have any effect on the game. The new hostnames are listed below.

I verified that the approach still works by setting all new hostnames to the IP of the desired region and ended up right where I expected.

```
gamelift-ping.us-east-1.api.aws
gamelift-ping.us-east-2.api.aws
gamelift-ping.us-west-1.api.aws
gamelift-ping.us-west-2.api.aws
gamelift-ping.ap-south-1.api.aws
gamelift-ping.ap-northeast-2.api.aws
gamelift-ping.ap-southeast-1.api.aws
gamelift-ping.ap-southeast-2.api.aws
gamelift-ping.ap-northeast-1.api.aws
gamelift-ping.ca-central-1.api.aws
gamelift-ping.eu-central-1.api.aws
gamelift-ping.eu-west-1.api.aws
gamelift-ping.eu-west-2.api.aws
gamelift-ping.sa-east-1.api.aws
```

**Comment by benxtmana** [comment]
how can i fix it?

**Comment by Kinuseka** [comment]
Thanks for the tip. If I may ask where did you get the information about these new endpoints.

**Comment by htmldoug** [comment]
Wireshark capture filtering on DNS during game startup.

**Comment by mvyiko** [comment]
thanks, these work!

**Comment by benxtmana** [comment]
> thanks, these work!

nah git hub people speaking a different language what did you do to fix that

**Comment by htmldoug** [comment]
For users looking for a workaround in the mean time, the easiest approach is to paste the following into your [hosts file](https://www.howtogeek.com/784196/how-to-edit-the-hosts-file-on-windows-10-or-11/), and delete the line of the region you *want* to connect to. Save it and restart the game.

```
0.0.0.0 gamelift-ping.us-east-1.api.aws
0.0.0.0 gamelift-ping.us-east-2.api.aws
0.0.0.0 gamelift-ping.us-west-1.api.aws
0.0.0.0 gamelift-ping.us-west-2.api.aws
0.0.0.0 gamelift-ping.ca-central-1.api.aws
0.0.0.0 gamelift-ping.eu-central-1.api.aws
0.0.0.0 gamelift-ping.eu-west-1.api.aws
0.0.0.0 gamelift-ping.eu-west-2.api.aws
0.0.0.0 gamelift-ping.sa-east-1.api.aws
0.0.0.0 gamelift-ping.ap-south-1.api.aws
0.0.0.0 gamelift-ping.ap-northeast-2.api.aws
0.0.0.0 gamelift-ping.ap-southeast-1.api.aws
0.0.0.0 gamelift-ping.ap-southeast-2.api.aws
0.0.0.0 gamelift-ping.ap-northeast-1.api.aws
```

**Comment by Jasbear-blip** [comment]
I made an account just so I could say I'm really glad I found this! 

I know it's bugged at the moment but I was up for hours trying to figure out why my block on SEA servers weren't working anymore so ty htmldoug for bringing it up! Will definitely use the region changer once it's updated for ease of access and just incase, really great work Kinuseka. :))

**Comment by Kinuseka** [comment]
Implemented on 1.2-rc1

**Comment by htmldoug** [comment]
As of today's patch, dbd has changed the hostnames back to the old ones. Whether or not they'll stay that way is anyone's guess. I suppose we could add entries for both of them...

**Comment by mvyiko** [comment]
> As of today's patch, dbd has changed the hostnames back to the old ones. Whether or not they'll stay that way is anyone's guess. I suppose we could add entries for both of them...

seems like they cant make up their mind
